basePath: /
info:
  contact: {}
  description: This is a sample Server pets
  license: {}
  title: Swagger Example API
  version: 0.0.1
paths:
  /login/:
    post:
      parameters:
      - description: Offset
        in: query
        name: limit
        required: true
        type: integer
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 用户登录
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: token
    type: apiKey
swagger: "2.0"
