basePath: /
info:
  contact: {}
  description: This is a sample Server pets
  license: {}
  title: Swagger Example API
  version: 0.0.1
paths:
  /login/:
    post:
      parameters:
      - description: 用户名
        in: query
        name: user_name
        required: true
        type: string
      - description: 密码
        in: query
        name: password
        required: true
        type: string
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 用户登录
      tags:
      - User
  /user/:
    get:
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 用户信息
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
